version: '3.8'

services:
  serviceuser:
    image: andres727/serviceuser
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user
      SPRING_DATASOURCE_USERNAME: devdb
      SPRING_DATASOURCE_PASSWORD: a1b2c3d4
    networks:
      - backend

  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: a1b2c3d4
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
